services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
      - database
    env_file:
      - .env.local

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
      - minio
    env_file:
      - .env.local

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    env_file:
      - .env.local

volumes:
  minio-data: