apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gcr.io/${GCP_PROJECT_ID}/api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_USER
          value: "${DATABASE_USER}"
        - name: DATABASE_PASSWORD
          value: "${DATABASE_PASSWORD}"
        - name: DATABASE_NAME
          value: "${DATABASE_NAME}"
        - name: DATABASE_HOST
          value: "database-service"
