apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "${DATABASE_NAME}"
        - name: POSTGRES_USER
          value: "${DATABASE_USER}"
        - name: POSTGRES_PASSWORD
          value: "${DATABASE_PASSWORD}"
