controller:
  service:
    type: LoadBalancer

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
    # Path for the API service
    - path: /api
      pathType: Prefix
      backend:
        service:
          name: api-service
          port:
            number: 5000

    # Path for the Webapp service
    - path: /
      pathType: Prefix
      backend:
        service:
          name: webapp-service
          port:
            number: 80
