name: Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'api/**'
      - 'webapp/**'
      - 'database/**'
      - '.github/**'
  
jobs:
  deploy-gke:
    runs-on: ubuntu-latest
    env:
      TF_VAR_google_credentials: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_clerk_publishable_key: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      TF_VAR_clerk_secret_key: ${{ secrets.CLERK_SECRET_KEY }}
      TF_VAR_clerk_sign_in_url: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
      TF_VAR_clerk_sign_up_url: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
      TF_VAR_clerk_webhook_secret: ${{ secrets.CLERK_WEBHOOK_SECRET }}
      TF_VAR_database_host: "database-service.default.svc.cluster.local"
      TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
      TF_VAR_next_public_api_url: "https://cloud.talecompendium.com/api"
      TF_VAR_next_public_webapp_url: "https://cloud.talecompendium.com"
      TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      TF_VAR_stripe_publishable_key: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      TF_VAR_stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: kubectl

      # Step 4: Configure kubectl to use the GKE cluster
      - name: Configure kubectl to use the GKE cluster
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

      # Step 5: Authenticate Docker to GCR
      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker

      # Step 6: Build and Push Docker Images for API only if files in the API directory have changed
      - name: Build and Push API Docker Image
        if: github.event_name == 'push' && (contains(github.event.head_commit.message, 'api/') || contains(github.event.commits[0].modified, 'api/'))
        run: |
          docker build \
            --no-cache \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            --build-arg STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} \
            --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
            --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            --build-arg NEXT_PUBLIC_API_URL="https://cloud.talecompendium.com/api" \
            --build-arg NEXT_PUBLIC_WEBAPP_URL="https://cloud.talecompendium.com" \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:${{ github.sha }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest \
            -f ./api/Dockerfile ./api

          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest

      # Step 7: Build and Push Webapp Docker Image only if files in the webapp directory have changed
      - name: Build and Push Webapp Docker Image
        if: github.event_name == 'push' && (contains(github.event.head_commit.message, 'webapp/') || contains(github.event.commits[0].modified, 'webapp/'))
        run: |
          docker build \
            --no-cache \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            --build-arg STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
            --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} \
            --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
            --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            --build-arg NEXT_PUBLIC_API_URL="https://cloud.talecompendium.com/api" \
            --build-arg NEXT_PUBLIC_WEBAPP_URL="https://cloud.talecompendium.com" \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp:${{ github.sha }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp:latest \
            -f ./webapp/Dockerfile ./webapp

          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp:latest

      # Step 7 Initialize Terraform and update lock file
      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init -upgrade

      # Step 8: Import existing resources before Terraform apply
      - name: Import webapp deployment
        working-directory: terraform
        run: |
          terraform import kubernetes_deployment.webapp default/webapp-deployment || echo "webapp-deployment does not exist, skipping import"

      - name: Import api deployment
        working-directory: terraform
        run: |
          terraform import kubernetes_deployment.api default/api-deployment || echo "api-deployment does not exist, skipping import"

      - name: Import database deployment
        working-directory: terraform
        run: |
          terraform import kubernetes_deployment.database default/database-deployment || echo "database-deployment does not exist, skipping import"

      - name: Import webapp service
        working-directory: terraform
        run: |
          terraform import kubernetes_service.webapp default/webapp-service || echo "webapp-service does not exist, skipping import"

      - name: Import api service
        working-directory: terraform
        run: |
          terraform import kubernetes_service.api default/api-service || echo "api-service does not exist, skipping import"

      - name: Import database service
        working-directory: terraform
        run: |
          terraform import kubernetes_service.database default/database-service || echo "database-service does not exist, skipping import"

      - name: Import ingress resource
        working-directory: terraform
        run: |
          terraform import kubernetes_manifest.webapp_ingress 'networking.k8s.io/v1,Ingress,default/webapp-ingress' || echo "webapp-ingress does not exist, skipping import"

      - name: Import SSL certificate
        working-directory: terraform
        run: |
          terraform import google_compute_managed_ssl_certificate.webapp_cert webapp-managed-cert || echo "webapp-managed-cert does not exist, skipping import"

      # Step 9: Terraform Apply (Image-related Resources)
      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve

      # Step 10: Conditional Cleanup of old Docker images
      - name: Cleanup old Docker images in GCR (for webapp)
        if: github.event_name == 'push' && (contains(github.event.head_commit.message, 'webapp/') || contains(github.event.commits[0].modified, 'webapp/'))
        run: |
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          # List all tags in the webapp image and delete those that aren't 'latest'
          gcloud container images list-tags gcr.io/${PROJECT_ID}/webapp --format='get(digest)' --filter='NOT tags:(latest)' | while read digest; do
            gcloud container images delete gcr.io/${PROJECT_ID}/webapp@$digest --quiet --force-delete-tags
          done

      - name: Cleanup old Docker images in GCR (for api)
        if: github.event_name == 'push' && (contains(github.event.head_commit.message, 'api/') || contains(github.event.commits[0].modified, 'api/'))
        run: |
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          # List all tags in the api image and delete those that aren't 'latest'
          gcloud container images list-tags gcr.io/${PROJECT_ID}/api --format='get(digest)' --filter='NOT tags:(latest)' | while read digest; do
            gcloud container images delete gcr.io/${PROJECT_ID}/api@$digest --quiet --force-delete-tags
          done
