name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure kubectl to use the GKE cluster
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Docker image for webapp
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
          --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
          --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
          --build-arg STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
          --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} \
          --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
          --build-arg CLERK_WEBHOOK_SECRET=${{ secrets.CLERK_WEBHOOK_SECRET }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
          --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
          -t gcr.io/nodal-clock-433208-b4/webapp:$GITHUB_SHA \
          -f ./webapp/Dockerfile ./webapp

    - name: Build Docker image for api
      run: |
        docker build \
          -t gcr.io/nodal-clock-433208-b4/api:$GITHUB_SHA \
          -f ./api/Dockerfile ./api

    - name: Push Docker image to GCR for webapp
      run: |
        docker push gcr.io/nodal-clock-433208-b4/webapp:$GITHUB_SHA

    - name: Push Docker image to GCR for api
      run: |
        docker push gcr.io/nodal-clock-433208-b4/api:$GITHUB_SHA

    - name: Clean up existing Kubernetes resources
      run: |
        kubectl delete deployment webapp-deployment api-deployment database-deployment || true
        kubectl delete service webapp-service api-service database-service || true
        kubectl delete pod --all || true

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init and Refresh State
      working-directory: terraform
      run: |
        terraform init
        terraform refresh

    - name: Terraform Import Resources
      working-directory: terraform
      run: |
        terraform import kubernetes_deployment.webapp default/webapp-deployment || true
        terraform import kubernetes_deployment.api default/api-deployment || true
        terraform import kubernetes_deployment.database default/database-deployment || true
        terraform import kubernetes_service.webapp default/webapp-service || true
        terraform import kubernetes_service.api default.api-service || true
        terraform import kubernetes_service.database default.database-service || true

    - name: Terraform Apply
      working-directory: terraform
      run: |
        terraform apply -auto-approve
