name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure kubectl to use the GKE cluster
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Docker image for webapp
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
          --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
          --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
          --build-arg STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
          --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} \
          --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
          --build-arg CLERK_WEBHOOK_SECRET=${{ secrets.CLERK_WEBHOOK_SECRET }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
          --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
          -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp:$GITHUB_SHA \
          -f ./webapp/Dockerfile ./webapp

    - name: Build Docker image for api
      run: |
        docker build \
          -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:$GITHUB_SHA \
          -f ./api/Dockerfile ./api

    - name: Push Docker image to GCR for webapp
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp:$GITHUB_SHA

    - name: Push Docker image to GCR for api
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:$GITHUB_SHA

    - name: Delete existing deployments and services (Cleanup)
      run: |
        kubectl delete deployment webapp-deployment || true
        kubectl delete deployment api-deployment || true
        kubectl delete deployment database-deployment || true
        kubectl delete service webapp-service || true
        kubectl delete service api-service || true
        kubectl delete service database-service || true

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init and Apply (with Import)
      working-directory: terraform
      env:
        TF_VAR_google_credentials: ${{ secrets.GCP_SA_KEY }}
        TF_VAR_clerk_publishable_key: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        TF_VAR_stripe_publishable_key: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
        TF_VAR_stripe_secret_key: ${{ secrets.STRIPE_SECRET_KEY }}
        TF_VAR_clerk_secret_key: ${{ secrets.CLERK_SECRET_KEY }}
        TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        TF_VAR_database_user: ${{ secrets.DATABASE_USER }}
        TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
        TF_VAR_database_name: ${{ secrets.DATABASE_NAME }}
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GKE_REGION }}
        TF_VAR_cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
      run: |
        terraform init
        terraform import kubernetes_deployment.webapp "default/webapp-deployment" || true
        terraform import kubernetes_deployment.api "default/api-deployment" || true
        terraform import kubernetes_deployment.database "default/database-deployment" || true
        terraform import kubernetes_service.webapp "default/webapp-service" || true
        terraform import kubernetes_service.api "default/api-service" || true
        terraform import kubernetes_service.database "default/database-service" || true
        terraform apply -auto-approve || terraform apply -refresh-only
